/* soapPraxiconTreePortBindingObject.h
   Generated by gSOAP 2.7.17 from quote.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapPraxiconTreePortBindingObject_H
#define soapPraxiconTreePortBindingObject_H
#include "soapH.h"

/******************************************************************************\
 *                                                                            *
 * Service Object                                                             *
 *                                                                            *
\******************************************************************************/

class PraxiconTreePortBindingService : public soap
{    public:
	PraxiconTreePortBindingService()
	{ static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns3", "http://jaxb.dev.java.net/array", NULL, NULL},
	{"ns1", "http://webservice.praxicon.poeticon.csri/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};

	this->namespaces = namespaces; };
	virtual ~PraxiconTreePortBindingService() { };
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog) { return soap_bind(this, host, port, backlog); };
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept() { return soap_accept(this); };
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve() { return soap_serve(this); };
};

/******************************************************************************\
 *                                                                            *
 * Service Operations (you should define these globally)                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__HelloWorld(struct soap*, ns1__HelloWorld *ns1__HelloWorld_, ns1__HelloWorldResponse *ns1__HelloWorldResponse_);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__queryPRAXICON(struct soap*, ns1__queryPRAXICON *ns1__queryPRAXICON_, ns1__queryPRAXICONResponse *ns1__queryPRAXICONResponse_);

#endif
