/* soapPraxiconTreePortBindingProxy.h
   Generated by gSOAP 2.7.17 from quote.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapPraxiconTreePortBindingProxy_H
#define soapPraxiconTreePortBindingProxy_H
#include "soapH.h"
class PraxiconTreePortBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'PraxiconTreePortBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	PraxiconTreePortBinding()
	{ soap = soap_new(); endpoint = "http://localhost:25191/PraxiconWebService/PraxiconTreeService"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns3", "http://jaxb.dev.java.net/array", NULL, NULL},
	{"ns1", "http://webservice.praxicon.poeticon.csri/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~PraxiconTreePortBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'HelloWorld' of service 'PraxiconTreePortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__HelloWorld(ns1__HelloWorld *ns1__HelloWorld_, ns1__HelloWorldResponse *ns1__HelloWorldResponse_) { return soap ? soap_call___ns1__HelloWorld(soap, endpoint, NULL, ns1__HelloWorld_, ns1__HelloWorldResponse_) : SOAP_EOM; };
	/// Invoke 'queryPRAXICON' of service 'PraxiconTreePortBinding' and return error code (or SOAP_OK)
	virtual int __ns1__queryPRAXICON(ns1__queryPRAXICON *ns1__queryPRAXICON_, ns1__queryPRAXICONResponse *ns1__queryPRAXICONResponse_) { return soap ? soap_call___ns1__queryPRAXICON(soap, endpoint, NULL, ns1__queryPRAXICON_, ns1__queryPRAXICONResponse_) : SOAP_EOM; };
};
#endif
